# Generated by Django 3.2.7 on 2022-04-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='audit_wealth',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.IntegerField(default=0)),
                ('month', models.CharField(default='', max_length=10)),
                ('year', models.IntegerField(default=0)),
                ('mutual_fund_name1', models.CharField(default='', max_length=20)),
                ('mutual_fund_investment1', models.DecimalField(decimal_places=3, max_digits=10)),
                ('mutual_fund_return1', models.DecimalField(decimal_places=3, max_digits=10)),
                ('mutual_fund_name2', models.CharField(default='', max_length=20)),
                ('mutual_fund_investment2', models.DecimalField(decimal_places=3, max_digits=10)),
                ('mutual_fund_return2', models.DecimalField(decimal_places=3, max_digits=10)),
                ('mutual_fund_name3', models.CharField(default='', max_length=20)),
                ('mutual_fund_investment3', models.DecimalField(decimal_places=3, max_digits=10)),
                ('mutual_fund_return3', models.DecimalField(decimal_places=3, max_digits=10)),
                ('mutual_fund_name4', models.CharField(default='', max_length=20)),
                ('mutual_fund_investment4', models.DecimalField(decimal_places=3, max_digits=10)),
                ('mutual_fund_return4', models.DecimalField(decimal_places=3, max_digits=10)),
                ('stocks_name1', models.CharField(default='', max_length=10)),
                ('stocks_investment1', models.DecimalField(decimal_places=3, max_digits=10)),
                ('stocks_return1', models.DecimalField(decimal_places=3, max_digits=10)),
                ('stocks_name2', models.CharField(default='', max_length=10)),
                ('stocks_investment2', models.DecimalField(decimal_places=3, max_digits=10)),
                ('stocks_return2', models.DecimalField(decimal_places=3, max_digits=10)),
                ('stocks_name3', models.CharField(default='', max_length=10)),
                ('stocks_investment3', models.DecimalField(decimal_places=3, max_digits=10)),
                ('stocks_return3', models.DecimalField(decimal_places=3, max_digits=10)),
                ('stocks_name4', models.CharField(default='', max_length=10)),
                ('stocks_investment4', models.DecimalField(decimal_places=3, max_digits=10)),
                ('stocks_return4', models.DecimalField(decimal_places=3, max_digits=10)),
                ('currency_name1', models.CharField(default='', max_length=10)),
                ('currency_investment1', models.DecimalField(decimal_places=3, max_digits=10)),
                ('currency_return1', models.DecimalField(decimal_places=3, max_digits=10)),
                ('currency_name2', models.CharField(default='', max_length=10)),
                ('currency_investment2', models.DecimalField(decimal_places=3, max_digits=10)),
                ('currency_return2', models.DecimalField(decimal_places=3, max_digits=10)),
                ('currency_name3', models.CharField(default='', max_length=10)),
                ('currency_investment3', models.DecimalField(decimal_places=3, max_digits=10)),
                ('currency_return3', models.DecimalField(decimal_places=3, max_digits=10)),
                ('currency_name4', models.CharField(default='', max_length=10)),
                ('currency_investment4', models.DecimalField(decimal_places=3, max_digits=10)),
                ('currency_return4', models.DecimalField(decimal_places=3, max_digits=10)),
                ('borrow_person1', models.CharField(default='', max_length=10)),
                ('borrow_amount1', models.DecimalField(decimal_places=3, max_digits=10)),
                ('borrow_person2', models.CharField(default='', max_length=10)),
                ('borrow_amount2', models.DecimalField(decimal_places=3, max_digits=10)),
                ('borrow_person3', models.CharField(default='', max_length=10)),
                ('borrow_amount3', models.DecimalField(decimal_places=3, max_digits=10)),
                ('lend_person1', models.CharField(default='', max_length=10)),
                ('lend_amount1', models.DecimalField(decimal_places=3, max_digits=10)),
                ('lend_person2', models.CharField(default='', max_length=10)),
                ('lend_amount2', models.DecimalField(decimal_places=3, max_digits=10)),
                ('lend_person3', models.CharField(default='', max_length=10)),
                ('lend_amount3', models.DecimalField(decimal_places=3, max_digits=10)),
                ('bank_balance', models.DecimalField(decimal_places=3, max_digits=10)),
                ('hand_cash', models.DecimalField(decimal_places=3, max_digits=10)),
                ('demat', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
