# Generated by Django 3.2.7 on 2022-04-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit_wealth',
            name='total_investment',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='audit_wealth',
            name='total_return',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
