# Generated by Django 4.0.4 on 2022-06-11 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220419_2345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='audit_wealth',
        ),
    ]
