# Generated by Django 4.0.4 on 2022-09-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_audit_wealth_bank_balance_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit_wealth',
            name='borrow_money_1',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='audit_wealth',
            name='borrow_money_2',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='audit_wealth',
            name='borrow_money_3',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
