# Generated by Django 4.0.4 on 2022-09-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_audit_wealth_borrow_money_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit_wealth',
            name='bank_balance_3',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='audit_wealth',
            name='bank_name_3',
            field=models.CharField(default='', max_length=10),
        ),
    ]
