# Generated by Django 4.0.4 on 2022-09-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_audit_wealth_bank_balance_3_audit_wealth_bank_name_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit_wealth',
            name='id',
        ),
        migrations.AddField(
            model_name='audit_wealth',
            name='record_id',
            field=models.AutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
