# Generated by Django 4.0.4 on 2022-09-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_audit_wealth_id_audit_wealth_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit_wealth',
            name='record_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
