# Generated by Django 4.0.4 on 2022-09-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_audit_wealth_record_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit_wealth',
            name='total_bank_balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='audit_wealth',
            name='total_borrow',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='audit_wealth',
            name='total_crypto_investment',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='audit_wealth',
            name='total_crypto_return',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='audit_wealth',
            name='total_lend',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
