# Generated by Django 4.0.4 on 2022-09-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_audit_wealth_total_bank_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit_wealth',
            name='bank_balance_1',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='bank_balance_2',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='bank_balance_3',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='borrow_money_1',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='borrow_money_2',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='borrow_money_3',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='cy_current_1',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='cy_current_2',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='cy_current_3',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='cy_current_4',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='cy_current_5',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='cy_invested_1',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='cy_invested_2',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='cy_invested_3',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='cy_invested_4',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='cy_invested_5',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='demat_balance',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='hand_balance',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='lend_money_1',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='lend_money_2',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='lend_money_3',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='mf_current_1',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='mf_current_2',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='mf_current_3',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='mf_current_4',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='mf_current_5',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='mf_invested_1',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='mf_invested_2',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='mf_invested_3',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='mf_invested_4',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='mf_invested_5',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_amount_1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_amount_10',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_amount_2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_amount_3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_amount_4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_amount_5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_amount_6',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_amount_7',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_amount_8',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_amount_9',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_buy_price_1',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_buy_price_10',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_buy_price_2',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_buy_price_3',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_buy_price_4',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_buy_price_5',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_buy_price_6',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_buy_price_7',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_buy_price_8',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_buy_price_9',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_current_price_1',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_current_price_10',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_current_price_2',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_current_price_3',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_current_price_4',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_current_price_5',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_current_price_6',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_current_price_7',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_current_price_8',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_current_price_9',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='total_Mutual_fund_investment',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='total_Mutual_fund_return',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='total_bank_balance',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='total_borrow',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='total_crypto_investment',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='total_crypto_return',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='total_investment',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='total_lend',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='total_return',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='total_stock_investment',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='total_stock_return',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
    ]
