# Generated by Django 4.0.4 on 2022-09-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_audit_wealth_total_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit_wealth',
            name='total_Mutual_fund_profit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='audit_wealth',
            name='total_crypto_profit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='audit_wealth',
            name='total_stock_profit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
    ]
