# Generated by Django 4.0.4 on 2022-09-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_audit_wealth_total_mutual_fund_profit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit_wealth',
            name='bank_name_1',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='bank_name_2',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='bank_name_3',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='cy_name_1',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='cy_name_2',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='cy_name_3',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='cy_name_4',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='cy_name_5',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='mf_name_1',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='mf_name_2',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='mf_name_3',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='mf_name_4',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='mf_name_5',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='person_name_borrow_1',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='person_name_borrow_2',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='person_name_borrow_3',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='person_name_lend_1',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='person_name_lend_2',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='person_name_lend_3',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_name_1',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_name_10',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_name_2',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_name_3',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_name_4',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_name_5',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_name_6',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_name_7',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_name_8',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='audit_wealth',
            name='st_name_9',
            field=models.CharField(default='', max_length=30),
        ),
    ]
